### ISSUE TITLE
Math library linking commented out

### ISSUE THREAD

**Issue by MarkMos** [PoulinV/AxiCLASS#1]
It looks like the math library linking has accidentally been commented out when removing the gsl libraries in the makefile, causing the compilation to fail when building the class binary ([Makefile line 167](https://github.com/PoulinV/AxiCLASS/blob/e2d798c5a60d9a893d21c9634fe1c98f55bdfa38/Makefile#L167)).

`class: $(TOOLS) $(SOURCE) $(EXTERNAL) $(OUTPUT) $(CLASS)`
	`$(CC) $(OPTFLAG) $(OMPFLAG) $(LDFLAG) $(GSLFLAG) -o class $(addprefix build/,$(notdir $^))`
`#-lgsl -lgslcblas -lm`

**Comment by ark93-cosmo** [comment]
Thank you for pointing that out!

**Comment by PoulinV** [comment]
it should have been corrected in the master now! sorry for that.
